# Generated by Django 3.1 on 2020-08-25 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
